import React, { useEffect, useState } from "react";
import { FaFilePdf, FaPrint } from "react-icons/fa";
import jsPDF from "jspdf";
import { API } from "../../http";

const Certificate= () => {
  const [companies, setCompanies] = useState([]);

  useEffect(() => {
    const fetchCompanies = async () => {
      try {
        const response = await API.get("company");
        if (response.status === 200) {
          setCompanies(response.data.data);
        } else {
          console.error("Failed to fetch companies");
        }
      } catch (error) {
        console.error("Error fetching companies:", error);
      }
    };

    fetchCompanies();
  }, []);

  const activeCompanies = companies.filter(
    (c) => c.renewStatus === "Active"
  );

  const generatePdf = (company) => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "pt",
      format: "a5",
    });

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Certificate of Registration", 210, 60, null, null, "center");

    doc.setDrawColor(0);
    doc.rect(20, 30, 400, 250);

    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`This certifies that`, 210, 110, null, null, "center");

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(`${company.companyNameEng}`, 210, 140, null, null, "center");

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(
      `with registration number ${company.registrationNo},`,
      210,
      170,
      null,
      null,
      "center"
    );
    doc.text(
      `is currently recognized as an Active Company.`,
      210,
      190,
      null,
      null,
      "center"
    );

    doc.setFontSize(10);
    doc.text("Issued by: Company Registry System", 210, 260, null, null, "center");

    doc.save(`${company.companyNameEng}_Certificate.pdf`);
  };

  const printCertificate = (company) => {
    const printWindow = window.open("", "_blank", "width=800,height=600");
    if (!printWindow) return;

    const htmlContent = `
    <html>
      <head>
        <title>Print Certificate</title>
        <style>
          * {
            box-sizing: border-box;
            font-family: 'Georgia', serif;
          }
          body {
            margin: 0;
            padding: 0;
            background-color: #fefce8;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
          }
          .certificate {
            width: 700px;
            height: 500px;
            border: 6px double #d4af37;
            padding: 30px;
            background-color: #fff;
            text-align: center;
            position: relative;
          }
          .certificate h1 {
            font-size: 28px;
            margin-bottom: 10px;
            color: #2d3748;
          }
          .certificate h2 {
            font-size: 20px;
            margin: 20px 0 10px;
            color: #1a202c;
          }
          .certificate p {
            font-size: 16px;
            color: #4a5568;
            margin: 8px 0;
          }
          .footer {
            position: absolute;
            bottom: 20px;
            left: 0;
            right: 0;
            font-size: 12px;
            color: #718096;
          }
        </style>
      </head>
      <body>
        <div class="certificate">
          <h1>Certificate of Registration</h1>
          <p>This is to certify that</p>
          <h2>${company.companyNameEng}</h2>
          <p>Registration Number: <strong>${company.registrationNo}</strong></p>
          <p>Status: <strong>${company.renewStatus}</strong></p>
          <p>is officially registered in our company registry system.</p>
          <div class="footer">Generated by Sindhuli Udhog Baidya Sangh • ${new Date().toLocaleDateString()}</div>
        </div>
        <script>
          window.onload = function () {
            window.print();
            setTimeout(() => window.close(), 500);
          };
        </script>
      </body>
    </html>`;

    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  return (
    <div className="p-8 bg-gray-100 min-h-screen">
      <h2 className="text-2xl font-semibold mb-6 text-gray-800">
        Print Certificate of Registration
      </h2>
      <div className="overflow-x-auto">
        <table className="min-w-full bg-white rounded-lg shadow border border-gray-300">
          <thead className="bg-gray-100 text-gray-700 uppercase text-xs font-semibold">
            <tr>
              <th className="p-3 text-left">Company Name & Email</th>
              <th className="p-3 text-left">Registration No</th>
              <th className="p-3 text-left">Status</th>
              <th className="p-3 text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {activeCompanies.length > 0 ? (
              activeCompanies.map((company, idx) => (
                <tr
                  key={company.id}
                  className={idx % 2 === 0 ? "bg-white" : "bg-gray-50"}
                >
                  <td className="p-3">
                    <div>
                      <div className="font-medium text-gray-900">
                        {company.companyNameEng}
                      </div>
                      <div className="text-xs text-gray-500">{company.email}</div>
                    </div>
                  </td>
                  <td className="p-3">{company.registrationNo}</td>
                  <td className="p-3">
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-semibold ${
                        company.renewStatus === "Active"
                          ? "bg-green-100 text-green-800"
                          : "bg-red-100 text-red-800"
                      }`}
                    >
                      {company.renewStatus}
                    </span>
                  </td>
                  <td className="p-3 flex justify-center gap-4">
                    <button
                      onClick={() => generatePdf(company)}
                      title="Download PDF"
                      className="text-red-600 hover:text-red-800"
                    >
                      <FaFilePdf size={20} />
                    </button>
                    <button
                      onClick={() => printCertificate(company)}
                      title="Print Certificate"
                      className="text-green-600 hover:text-green-800"
                    >
                      <FaPrint size={20} />
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={4} className="text-center p-4 text-gray-500">
                  No active companies found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Certificate;
