import React, { useEffect, useState } from "react";

import { FaFilePdf, FaPrint } from "react-icons/fa";
import jsPDF from "jspdf";
import { API } from "../../http";

const IdCard = () => {
  const [companies, setCompanies] = useState([]);

  // Fetch companies on mount
  useEffect(() => {
    const fetchCompanies = async () => {
      try {
        const response = await API.get("company");
        if (response.status === 200) {
          setCompanies(response.data.data);
        } else {
          console.error("Failed to fetch companies");
        }
      } catch (error) {
        console.error("Error fetching companies:", error);
      }
    };

    fetchCompanies();
  }, []);

  // Filter only active companies (renewStatus === "Active")
  const activeCompanies = companies.filter(
    (c) => c.renewStatus === "Active"
  );

  // Generate PDF (company ID card style)
  const generatePdf = (company) => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "pt",
      format: [300, 200],
    });

    // Background and header
    doc.setFillColor(33, 150, 243);
    doc.rect(0, 0, 300, 50, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Company ID Card", 150, 35, null, null, "center");

    // Company details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");

    doc.text(`Name: ${company.companyNameEng || ""}`, 20, 80);
    doc.text(`Email: ${company.email || ""}`, 20, 100);
    doc.text(`Reg No: ${company.registrationNo || ""}`, 20, 120);
    doc.text(`Status: ${company.renewStatus || ""}`, 20, 140);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("Generated by Your System", 150, 180, null, null, "center");

    doc.save(`${company.companyNameEng}_IDCard.pdf`);
  };

  // Print ID card in new window and trigger print
const printCard = (company) => {
  const initials = company.companyNameEng
    ?.split(" ")
    .map((word) => word[0])
    .join("")
    .toUpperCase();

  const printWindow = window.open("", "_blank", "width=400,height=600");
  if (!printWindow) return;

  const htmlContent = `
    <html>
      <head>
        <title>Company ID Card</title>
        <style>
          * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          }
          body {
            background-color: #f3f4f6;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
          }
          .card {
            width: 320px;
            background: white;
            border-radius: 16px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
            padding: 20px;
            text-align: center;
          }
          .card-header {
            background: linear-gradient(to right, #3b82f6, #06b6d4);
            color: white;
            padding: 12px;
            font-size: 20px;
            font-weight: bold;
            border-radius: 12px 12px 0 0;
          }
          .badge {
            width: 60px;
            height: 60px;
            margin: 16px auto;
            background: #2563eb;
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 22px;
            font-weight: bold;
          }
          .info {
            text-align: left;
            margin-top: 10px;
          }
          .info p {
            margin: 6px 0;
            font-size: 14px;
            color: #374151;
          }
          .info p strong {
            color: #111827;
            width: 100px;
            display: inline-block;
          }
          .footer {
            font-size: 10px;
            color: #9ca3af;
            text-align: center;
            margin-top: 12px;
            border-top: 1px solid #e5e7eb;
            padding-top: 6px;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="card-header">Company ID Card</div>
          <div class="badge">${initials}</div>
          <div class="info">
            <p><strong>Name:</strong> ${company.companyNameEng || ""}</p>
            <p><strong>Email:</strong> ${company.email || ""}</p>
            <p><strong>Reg No:</strong> ${company.registrationNo || ""}</p>
            <p><strong>Status:</strong> ${company.renewStatus || ""}</p>
          </div>
          <div class="footer">Generated by Sindhuli Udhog Baidya Sangh</div>
        </div>
        <script>
          window.onload = function () {
            window.print();
            setTimeout(() => window.close(), 500);
          }
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
};



  return (
    <div className="p-8 bg-gray-100 min-h-screen">
      <h2 className="text-2xl font-semibold mb-6 text-gray-800">
        print Id Card
      </h2>
      <div className="overflow-x-auto">
        <table className="min-w-full bg-white rounded-lg shadow border border-gray-300">
          <thead className="bg-gray-100 text-gray-700 uppercase text-xs font-semibold">
            <tr>
              <th className="p-3 text-left">Company Name & Email</th>
              <th className="p-3 text-left">Registration No</th>
              <th className="p-3 text-left">Status</th>
              <th className="p-3 text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {activeCompanies.length > 0 ? (
              activeCompanies.map((company, idx) => (
                <tr
                  key={company.id}
                  className={idx % 2 === 0 ? "bg-white" : "bg-gray-50"}
                >
                  <td className="p-3">
                    <div>
                      <div className="font-medium text-gray-900">
                        {company.companyNameEng}
                      </div>
                      <div className="text-xs text-gray-500">{company.email}</div>
                    </div>
                  </td>
                  <td className="p-3">{company.registrationNo}</td>
                  <td className="p-3">
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-semibold ${
                        company.renewStatus === "Active"
                          ? "bg-green-100 text-green-800"
                          : "bg-red-100 text-red-800"
                      }`}
                    >
                      {company.renewStatus}
                    </span>
                  </td>
                  <td className="p-3 flex justify-center gap-4">
                    <button
                      onClick={() => generatePdf(company)}
                      title="Download PDF"
                      className="text-red-600 hover:text-red-800"
                    >
                      <FaFilePdf size={20} />
                    </button>
                    <button
                      onClick={() => printCard(company)}
                      title="Print ID Card"
                      className="text-green-600 hover:text-green-800"
                    >
                      <FaPrint size={20} />
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan={4}
                  className="text-center p-4 text-gray-500"
                >
                  No active companies found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default IdCard;
